### ISSUE TITLE
暗黑模式，字幕染色，下划线相关。

### ISSUE THREAD

**Issue by libregd** [tangshimin/qwerty-learner-desktop#10]
- 抄写过的内容也染色，可以试一下，我以前试过，在暗黑模式下很多行的绿色，感觉不好看，就改成染一行。
- 不是有下划线吗，把下划线加粗？

_Originally posted by @tangshimin in https://github.com/tangshimin/qwerty-learner-desktop/issues/9#issuecomment-1125263499_

**Comment by libregd** [comment]
![1](https://user-images.githubusercontent.com/59383867/168191546-e9f29a8f-b3ff-41a6-9cb8-cb00a92f8406.gif)
深色模式切换，会有这种只洗脸不洗澡的情况。

**Comment by tangshimin** [comment]
这个 bug 昨天晚上已经修复了

**Comment by libregd** [comment]
个人觉得可以把侧边栏的错误颜色和主色调安排在一个位置，其实一般错误红色没人改，因为红色=错误，认知深入人心了。preview的颜色稍微有点奇怪，换成主色调文字和待输入文字，错误文字三个颜色+背景色的体现可能会体验更好。
![image](https://user-images.githubusercontent.com/59383867/168209715-b0571e17-7c84-42e3-b61d-6fd15b7078db.png)

**Comment by libregd** [comment]
调整了一下光明黑暗模式的切换效果, 其实没有大改，就是改了一下文本透明度
- focus line text color：#000/ #fff  ，opacity 85% 
- writed lines text color： primary color, opacity  45%
- waiting lines text color：#000/#fff  , opacity 25%

![image](https://user-images.githubusercontent.com/59383867/168210075-4126c8b0-4451-40cc-88ab-4a6383cbd2e4.png)

**Comment by tangshimin** [comment]
- 错误颜色是针对红-绿色盲的，这个功能先设计，然后才设计的更改主色调。有了更改主色调，可以把主色调改成非绿色。
修改错误颜色确实可以删除了。

- 颜色选择对话框的预览区域可以调整。

**Comment by tangshimin** [comment]
> 调整了一下光明黑暗模式的切换效果, 其实没有大改，就是改了一下文本透明度
> 
>     * focus line text color：#000/ #fff  ，opacity 85%
> 
>     * writed lines text color： primary color, opacity  45%
> 
>     * waiting lines text color：#000/#fff  , opacity 25%
> 
> 
> ![image](https://user-images.githubusercontent.com/59383867/168210075-4126c8b0-4451-40cc-88ab-4a6383cbd2e4.png)

这种样式不错，我当初是没有想到调整透明度。

**Comment by tangshimin** [comment]
@libregd 这种预览效果怎么样？

![Snipaste8](https://user-images.githubusercontent.com/16540656/168430533-7d2d5ad5-1347-4b25-8c97-f17739f8c9fe.png)

**Comment by tangshimin** [comment]
我想把主色调换成四个字的名称，又不知道可以有什么名字可以替换。

![Snipaste9](https://user-images.githubusercontent.com/16540656/168430777-43c2bc0d-2e2a-457e-9070-5834bd5f13b3.png)

**Comment by libregd** [comment]
__https://github.com/tangshimin/qwerty-learner-desktop/issues/10#issuecomment-1126731620:__
选择主色，更改配色。

**Comment by libregd** [comment]
__https://github.com/tangshimin/qwerty-learner-desktop/issues/10#issuecomment-1126729607:__

完成度很高，就是为什么不能错误颜色放到这里？也就是还得重新另外打开错误颜色。

**Comment by tangshimin** [comment]
错误颜色不修改了，就固定为红色

**Comment by tangshimin** [comment]
不修改，就没有添加。

**Comment by tangshimin** [comment]
> **[#10 (comment)](https://github.com/tangshimin/qwerty-learner-desktop/issues/10#issuecomment-1126731620):** 选择主色，更改配色。

就改成，选择主色

**Comment by tangshimin** [comment]
- 视频播放快捷键改成了 `Tab` 键
- `Enter` 、`↓`  移动到下一行
- `←`、`→` 左右移动水平滚动条
- 行间距也缩小到 10px 

字幕内容的宽度暂时还不能修改。
<br>
![Snipaste 10](https://user-images.githubusercontent.com/16540656/168469848-b56d9c36-0394-4ce2-9eee-10fed01ecbd7.png)
![Snipaste 11](https://user-images.githubusercontent.com/16540656/168469845-522ca944-4449-4606-8f1f-677c2b38bc63.png)

**Comment by tangshimin** [comment]
这次更改和以前的配置信息不兼容，删除了选择错误颜色，所以如果不想重置默认配置（不会影响正在记忆的词库，和抄写字幕功能，主要是主色调的颜色，和音量），需要打开 `C:\Users\用户名\.qwerty-learner` 文件夹，然后再打开 `AppSettings.json` ,然后再删除 `wrongColorValue` 那一行，然后保存，然后再安装最新的版本。


![Snipaste 12](https://user-images.githubusercontent.com/16540656/168483723-d8b0da00-a57a-405b-a1f8-704907352598.png)
