### ISSUE TITLE
mac os 版本安装失败

### ISSUE THREAD

**Issue by libregd** [tangshimin/qwerty-learner-desktop#11]
“qwerty-learner”已损坏，无法安装，放到废纸篓“
- 操作系统：macOS Big Sur, 11.6.2
- VCL 安装版本：vlc-3.0.17.3-intel64.dmg
- 软件安装版本：qwerty-learner-1.0.0-beta9.dmg

**Comment by tangshimin** [comment]
安装成功了吗？

**Comment by libregd** [comment]
还是一样，任何来源通过终端设置好了。但是重新安装依旧是损坏。

**Comment by tangshimin** [comment]
没有把程序移到废纸篓吧? 试一下这个命令：

```shell
sudo xattr -rd com.apple.quarantine /Applications/qwerty-learner.app
```
参考链接：https://macwk.com/article/macos-file-damage

**Comment by gy-l** [comment]
> 没有把程序移到废纸篓吧? 试一下这个命令：
> 
> ```shell
> sudo xattr -rd com.apple.quarantine /Applications/qwerty-learner.app
> ```

执行完了会闪退

**Comment by tangshimin** [comment]
> > 没有把程序移到废纸篓吧? 试一下这个命令：
> > ```shell
> > sudo xattr -rd com.apple.quarantine /Applications/qwerty-learner.app
> > ```
> 
> 执行完了会闪退

qwerty-learner 闪退？

**Comment by gy-l** [comment]
macOs Catalina 10.15.7 
软件安装版本：qwerty-learner-1.0.0-beta9.dmg

**Comment by tangshimin** [comment]
> > 没有把程序移到废纸篓吧? 试一下这个命令：
> > ```shell
> > sudo xattr -rd com.apple.quarantine /Applications/qwerty-learner.app
> > ```
> 
> 执行完了会闪退

有没有设置任何来源
<br>
![Snipaste 13](https://user-images.githubusercontent.com/16540656/168614032-8168cdf1-a115-45c4-b654-739aebe0d44c.png)

**Comment by gy-l** [comment]
> > > 没有把程序移到废纸篓吧? 试一下这个命令：
> > > ```shell
> > > sudo xattr -rd com.apple.quarantine /Applications/qwerty-learner.app
> > > ```
> > 
> > 
> > 执行完了会闪退
> 
> 有没有设置任何来源 ![Snipaste 13](https://user-images.githubusercontent.com/16540656/168614032-8168cdf1-a115-45c4-b654-739aebe0d44c.png)

这个任何来源一直都是开着的

**Comment by gy-l** [comment]
刚刚试了一下beta8也是一样的情况，哥，加油。

**Comment by tangshimin** [comment]
> 

命令是手输的还是复制粘贴的？quarantine 后面要有空格。
参考链接：https://macwk.com/article/macos-file-damage

**Comment by gy-l** [comment]
> ```shell
> sudo xattr -rd com.apple.quarantine /Applications/qwerty-learner.app
> ```



> > 
> 
> 命令是手输的还是复制粘贴的？quarantine 后面要有空格。 参考链接：https://macwk.com/article/macos-file-damage

我应该没输错
![截屏2022-05-17 下午6 15 04](https://user-images.githubusercontent.com/15245259/168788862-208e5210-c5bf-4e87-98cb-f6f99b0e332b.png)
还是闪退了

**Comment by tangshimin** [comment]
输入密码

**Comment by tangshimin** [comment]
密码输入了吗

**Comment by gy-l** [comment]
> 密码输入了吗

输了的

**Comment by tangshimin** [comment]
> > ```shell
> > sudo xattr -rd com.apple.quarantine /Applications/qwerty-learner.app
> > ```
> 
> > > 
> > 
> > 
> > 命令是手输的还是复制粘贴的？quarantine 后面要有空格。 参考链接：https://macwk.com/article/macos-file-damage
> 
> 我应该没输错 ![截屏2022-05-17 下午6 15 04](https://user-images.githubusercontent.com/15245259/168788862-208e5210-c5bf-4e87-98cb-f6f99b0e332b.png) 还是闪退了

先把 <b>安全性与隐私 -> 通用 </b> 下面的那个锁解开，然后再输入命令。

**Comment by libregd** [comment]
__https://github.com/tangshimin/qwerty-learner-desktop/issues/11#issuecomment-1128368959__

我这边可以运行了，就是这条，按着你的建议。

**Comment by gy-l** [comment]
> > > ```shell
> > > sudo xattr -rd com.apple.quarantine /Applications/qwerty-learner.app
> > > ```
> > 
> > 
> > > > 
> > > 
> > > 
> > > 命令是手输的还是复制粘贴的？quarantine 后面要有空格。 参考链接：https://macwk.com/article/macos-file-damage
> > 
> > 
> > 我应该没输错 ![截屏2022-05-17 下午6 15 04](https://user-images.githubusercontent.com/15245259/168788862-208e5210-c5bf-4e87-98cb-f6f99b0e332b.png) 还是闪退了
> 
> 先把 安全性与隐私 -> 通用 下面的那个锁解开，然后再输入命令。

我这边也可以运行了，太棒了🌹
