### ISSUE TITLE
从文本生成词汇词库的问题

### ISSUE THREAD

**Issue by libregd** [tangshimin/qwerty-learner-desktop#12]
- 经常会生成的词库有数字和简单词汇：比如人称代词，数词，介词，这些是不太需要的：1，me ，you，him，to， on，
> 然后解决办法是自己弄了一个txt，把这些简单词汇整理好，希望生成一个词库，来去重：常见代词，数词，介词。

但是txt一分析，倒是去除得很干净，就很尴尬，这个应该怎么解决？

- 还有一个情况，生成的词库的单词顺序问题，我从文本导入，希望单词熟悉一些了，再去看和阅读，这样效率就起来了。但是生成的词库顺序完全是乱的，能不能按顺序呢，就是生成的词库，顺序上是遵照它第一次出现的顺序，这样我导入一本书，8000个词，我学习的时候是每天大概30个，那么我就按顺序chapter走就行了。达到复习预习巩固的作用。

**Comment by tangshimin** [comment]
你把简单词汇写到一个txt 然后生成词库，下一次生成词库的时候，选择：最近生成的词库， 过滤就可以了。
![Snipaste 14](https://user-images.githubusercontent.com/16540656/168708946-24101c86-8bea-4c06-98b3-e6920c240ec1.png)
<br>
过滤简单的单词可以选择：内置词库里的，牛津核心3000词或 5000词
![Snipaste 15](https://user-images.githubusercontent.com/16540656/168709103-cc4ed2bb-2bce-4849-bf6b-1a68d36c7e0c.png)

**Comment by tangshimin** [comment]
可以保存生成词库的顺序，但是生成词库的时间可能会慢一些。

**Comment by libregd** [comment]
__https://github.com/tangshimin/qwerty-learner-desktop/issues/12#issuecomment-1128305765__
可以理解生成会慢，现在这个已经很快了。而且计算机的速度价值不大，它背得了，我还没有背得。
__https://github.com/tangshimin/qwerty-learner-desktop/issues/12#issuecomment-1128305091__
我就是这么做的，但是卡在了txt生成词库那里，txt里面写了its，an，6，等。但是生成的词库没有its，an，6，那么自然过滤不掉待过滤词库里的an，its，6。

还是说txt格式有要求？我是直接用逗号分隔，有些中文逗号，有些中文逗号，有些换行了，有些没换行。

**Comment by tangshimin** [comment]
格式没有要求，跟 NLP 分词有关

**Comment by tangshimin** [comment]
最好还是用换行

**Comment by libregd** [comment]
__https://github.com/tangshimin/qwerty-learner-desktop/issues/12#issuecomment-1128321208__
感谢，换行就完全ok了，按顺序可以暂时先分析右边/下面 加个勾选框？

**Comment by tangshimin** [comment]
> **[#12 (comment)](https://github.com/tangshimin/qwerty-learner-desktop/issues/12#issuecomment-1128321208)** 感谢，换行就完全ok了，按顺序可以暂时先分析右边/下面 加个勾选框？

修改成默认保持单词在文档中出现的顺序了。
