### ISSUE TITLE
导入了mkv文件

### ISSUE THREAD

**Issue by wetery** [tangshimin/qwerty-learner-desktop#4]
![image](https://user-images.githubusercontent.com/20521189/163663116-cf1abdb6-894f-4971-bac8-f11e51281573.png)
然后就卡了

**Comment by tangshimin** [comment]
导入的是什么文件？

**Comment by wetery** [comment]
一部美剧的mkv文件
![image](https://user-images.githubusercontent.com/20521189/163663578-642bfa9c-9956-4300-9cc8-02a3f52a8278.png)

**Comment by wetery** [comment]
程序启动的时候就会出现
![image](https://user-images.githubusercontent.com/20521189/163663621-f34d2bda-49ae-4391-9431-b76775b1eb03.png)

**Comment by tangshimin** [comment]
磁链接是多少？我下载下来测试一下

**Comment by wetery** [comment]
是不是系统的问题，我现在用的是windows，除了基础功能能用，其他我都用不了，导入文档，也是空白的，字幕也空白的，都分析不出来

**Comment by tangshimin** [comment]
我也是 windows ,你的是不是 64 位的

**Comment by wetery** [comment]
是64的，那个视频我找不到在哪下载的了，是之前下载的

**Comment by wetery** [comment]
![image](https://user-images.githubusercontent.com/20521189/163663823-fb44a60c-2505-4ca4-b2b1-e79c7eb2d3ce.png)
![image](https://user-images.githubusercontent.com/20521189/163663835-5648bc8a-104b-42c6-8b84-2709ab173fee.png)
文档是这样的，分析之后找不到单词

**Comment by tangshimin** [comment]
> 程序启动的时候就会出现 ![image](https://user-images.githubusercontent.com/20521189/163663621-f34d2bda-49ae-4391-9431-b76775b1eb03.png)
我看你本地已经安装了 VLC ，把 `src\main\kotlin\player\MediaPlayerComponent.kt` 的 31行 到 36行注释成这样再试一下
![test](https://user-images.githubusercontent.com/16540656/163663874-9660fdaf-139d-4294-8a68-6e67f21fd093.png)

**Comment by tangshimin** [comment]
我马上打包一个 windows msi 安装包

**Comment by wetery** [comment]
> > 程序启动的时候就会出现 ![image](https://user-images.githubusercontent.com/20521189/163663621-f34d2bda-49ae-4391-9431-b76775b1eb03.png)
> > 我看你本地已经安装了 VLC ，把 `src\main\kotlin\player\MediaPlayerComponent.kt` 的 31行 到 36行注释成这样再试一下
> > ![test](https://user-images.githubusercontent.com/16540656/163663874-9660fdaf-139d-4294-8a68-6e67f21fd093.png)

代码我没改，我把本地的vlc卸载了，不会出现上面那些错误了，可还是导入不了mkv文件
![image](https://user-images.githubusercontent.com/20521189/163664519-1e3429e8-dbac-495a-8874-d40a601fc843.png)

**Comment by tangshimin** [comment]
这个应用我只在两台电脑上测试过，一台 windows 11 64位，一台很老的 Mac mini。所以在其它电脑上可能还会有各种各样的 bug。

**Comment by tangshimin** [comment]
> 

这是 MKV 文件的问题，你要不试试不同的 MKV 文件

**Comment by tangshimin** [comment]
> ![image](https://user-images.githubusercontent.com/20521189/163663823-fb44a60c-2505-4ca4-b2b1-e79c7eb2d3ce.png) ![image](https://user-images.githubusercontent.com/20521189/163663835-5648bc8a-104b-42c6-8b84-2709ab173fee.png) 文档是这样的，分析之后找不到单词

不能从文档生成词库是我万万没有想到的，难道 `.db `文件不能移植到不同的电脑?

**Comment by tangshimin** [comment]
@wetery ，我上传了一个 windows 安装包，你要不要试一下，https://github.com/tangshimin/qwerty-learner-desktop/releases/tag/v1.0.0-beta

**Comment by wetery** [comment]
在试那个安装包了，可是我没有mkv文件，你能把你成功的那个mkv文件发给我吗

**Comment by tangshimin** [comment]
从文档生成词库，还有没有问题



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年4月16日(星期六) 下午2:56
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [tangshimin/qwerty-learner-desktop] 导入了mkv文件 (Issue #4)




 
在试那个安装包了，可是我没有mkv文件，你能把你成功的那个mkv文件发给我吗

**Comment by wetery** [comment]
> 从文档生成词库，还有没有问题
> […](#)
> ---原始邮件--- 发件人: ***@***.***&gt; 发送时间: 2022年4月16日(星期六) 下午2:56 收件人: ***@***.***&gt;; 抄送: ***@***.******@***.***&gt;; 主题: Re: [tangshimin/qwerty-learner-desktop] 导入了mkv文件 (Issue #4) 在试那个安装包了，可是我没有mkv文件，你能把你成功的那个mkv文件发给我吗 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: ***@***.***&gt;

这个没问题

**Comment by tangshimin** [comment]
> 在试那个安装包了，可是我没有mkv文件，你能把你成功的那个mkv文件发给我吗

https://durian.blender.org/download/

**Comment by tangshimin** [comment]
刚刚那个测试版有问题，输入字符后，正确字符的颜色变成了红色叠加绿色，昨晚测试后没有改回来。
新版地址：https://github.com/tangshimin/qwerty-learner-desktop/releases/tag/v1.0.0-beta

**Comment by wetery** [comment]
从mkv生成词库要多久，我这个视频250M，50多分钟，链接是这个https://1337x.to/torrent/5219822/Sanditon-S02E05-720p-WEB-x265-MiNX-TGx/
https://1337x.to/torrent/5219822/Sanditon-S02E05-720p-WEB-x265-MiNX-TGx/

**Comment by tangshimin** [comment]
> 从mkv生成词库要多久，我这个视频250M，50多分钟，链接是这个https://1337x.to/torrent/5219822/Sanditon-S02E05-720p-WEB-x265-MiNX-TGx/ https://1337x.to/torrent/5219822/Sanditon-S02E05-720p-WEB-x265-MiNX-TGx/

跟从文档生成词库的速度差不多，你的意思是从这个视频生成词库花费了50分钟？

**Comment by wetery** [comment]
没有，一直卡着，根本生成不了，我是不知道要等多久，可以确定它game over，也没说有什么错
![image](https://user-images.githubusercontent.com/20521189/163670684-e6b79713-0a1f-4538-b31b-3690e315072a.png)

**Comment by tangshimin** [comment]
是 `ebml-reader ` 这个程序包的 bug

**Comment by tangshimin** [comment]
这是我最近重构时引入的 bug，我以前的测试视频都解析不了

**Comment by wetery** [comment]
还是不行，导入不了视频，也导入不了文档，这个源码打开的我就只能打打单词

**Comment by wetery** [comment]
不过这个项目demo看了，觉得没有实现你说的一边看剧，一边背单词。只是有了更丰富的词库，和可以结合具体情景。

**Comment by wetery** [comment]
一边看视频，一边背单词。我想要的是一部美剧，根据它的字幕，可以根据用户的水平，筛选出相应的单词，比如小学六年纪，高中，四级，生成词库，然后这个词库以弹幕的形式出现，出现一个，拼写一个

**Comment by tangshimin** [comment]
应该修复了，你重新下载，我刚刚上传的安装包试试。https://github.com/tangshimin/qwerty-learner-desktop/releases/tag/v1.0.0-beta

**Comment by tangshimin** [comment]
> 还是不行，导入不了视频，也导入不了文档，这个源码打开的我就只能打打单词

文档也不行吗？刚刚不是说从文档生成词库可以吗？

**Comment by wetery** [comment]
源码运行的那个，两种方式都不行的，应该是java的问题吧，说有什么东西找不到

**Comment by tangshimin** [comment]
缺少 slf4j 程序包，刚刚我已经添加依赖，重新打包了

**Comment by wetery** [comment]
![image](https://user-images.githubusercontent.com/20521189/163676606-05f7b395-7251-49ee-b6bb-0d86562e702a.png)
还是不行，你确定这个包是最新的，它显示是四小时前的

**Comment by tangshimin** [comment]
我在以前的那个页面编辑，重新上传的

**Comment by tangshimin** [comment]
你下载下来看最后修改时间是不是 21:04
![demo](https://user-images.githubusercontent.com/16540656/163676790-c83a2570-dbf8-48bd-8360-cf859f41a083.png)

**Comment by tangshimin** [comment]
> 

重新下载之后看不到我在本机的最后修改时间

**Comment by tangshimin** [comment]
> 源码运行的那个，两种方式都不行的，应该是java的问题吧，说有什么东西找不到

确实还有问题，是slf4j 程序包添加错了。可能是因为 IDEA 缓存的原因，只能在我的 windows 机器上运行，我刚刚在 Mac mini 上也运行不了。

**Comment by tangshimin** [comment]
我在 Windows 和 Mac mini 上测试【从MKV 文件生成词库】都成功了。

**Comment by tangshimin** [comment]
> 我在 Windows 和 Mac mini 上测试【从MKV 文件生成词库】都成功了。

我错了，我在 Mac mini 上只测试了读取 MKV 视频文件，我看到MKV视频文件读取成功之后就把对话框关了，还有一个 bug，读取本地词典还是不行。

**Comment by tangshimin** [comment]
windows 版的 msi 安装包应该没有问题，本地词库是一个大文件(265 MB)使用了 [Git Large File Storage (LFS)](https://git-lfs.github.com/),需要下载安装[LFS](https://git-lfs.github.com/) 然后使用 `git lfs pull` 重新拉取大文件,拉取大文件之后再重新启动应该不会有问题了。

**Comment by wetery** [comment]
![image](https://user-images.githubusercontent.com/20521189/163994995-ddad4914-9fa4-41bc-83c1-7b863a0f858b.png)
大佬可以了，windows安装包的，但这个过滤词库应该多加个过滤掉牛津核心5000词的吧，要不然好多词都太简单了

**Comment by wetery** [comment]
![image](https://user-images.githubusercontent.com/20521189/163995789-ae4f478b-93dc-4070-a97e-d52ec92fe745.png)
这个可以看视频的功能没见到，我导入了mkv文件后，还是跟导入文档或者字幕文件一样

**Comment by tangshimin** [comment]
![Snipaste_2022-04-19_19-45-07](https://user-images.githubusercontent.com/16540656/163996296-d4307ddc-cee3-4279-afab-b35edc668111.png)

**Comment by tangshimin** [comment]
> 
![Snipaste_2022-04-19_19-47-11](https://user-images.githubusercontent.com/16540656/163996741-41cae6ca-b81c-46ae-9759-7c8989267f5d.png)

**Comment by wetery** [comment]
那个视频的声音太小的，我声音调到最大后，单词的声音又太大的

**Comment by tangshimin** [comment]
单词发音和视频播放用的是同一个音量，看来需要分成两个功能了。



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年4月19日(星期二) 晚上8:08
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [tangshimin/qwerty-learner-desktop] 导入了mkv文件 (Issue #4)




 
那个视频的声音太小的，我声音调到最大后，单词的声音又太大的

**Comment by tangshimin** [comment]
这个是不是从 ASS 字幕生成的词库？

**Comment by wetery** [comment]
而且我刚刚用着用着不知道怎么就退出了，然后也启动不了，我是重新安装才能用的

**Comment by tangshimin** [comment]
> ![image](https://user-images.githubusercontent.com/20521189/164008357-57344f9e-1569-42ac-8d42-699e20712abc.png) 有些字幕前面会多个{\an1}

是美剧吗？

**Comment by wetery** [comment]
https://1337x.to/torrent/5219822/Sanditon-S02E05-720p-WEB-x265-MiNX-TGx/

**Comment by wetery** [comment]
英剧来的，好久没看英美剧，不查分不太清

**Comment by tangshimin** [comment]
字幕前面有特殊字符和音量控制都修复了，下载地址：
https://github.com/tangshimin/qwerty-learner-desktop/releases/tag/v1.0.0-beta2
