### ISSUE TITLE
导入文件错误后，会崩溃退出，重开直接上次错误弹窗，继续崩溃，进入一种循环

### ISSUE THREAD

**Issue by libregd** [tangshimin/qwerty-learner-desktop#7]
环境： win10 64bit 
- 先导入了一个常规pdf（全是可复制的字）→ 变成 json → 导入json → 过筛单词 → 顺利打字
- 再导入了这个pdf （字也可复制，但是排版四格漫画，同时有较多图片）→ 变成json 失败 → 关闭崩溃强退 → 重开 → 截图如下 → 关闭消失 → 重开 → 截图如下 →……
![image](https://user-images.githubusercontent.com/59383867/167261145-58649255-87f6-4eda-a328-0098ae648f22.png)

- task manager 能看到任务进程 → 杀死 → 重开 → 截图如上

**Comment by tangshimin** [comment]
确实是一个bug, `C:\Users\用户名\.qwerty-learner` 文件夹里的配置信息全部删掉再启动，就可以暂时避开这个 bug。

**Comment by tangshimin** [comment]
修复了词库解析错误相关的bug,不会循环的弹出词库解析错误对话框了。

**Comment by tangshimin** [comment]
> 环境： win10 64bit
> 
>     * 先导入了一个常规pdf（全是可复制的字）→ 变成 json → 导入json → 过筛单词 → 顺利打字
> 
>     * 再导入了这个pdf （字也可复制，但是排版四格漫画，同时有较多图片）→ 变成json 失败 → 关闭崩溃强退 → 重开 → 截图如下 → 关闭消失 → 重开 → 截图如下 →……
>       ![image](https://user-images.githubusercontent.com/59383867/167261145-58649255-87f6-4eda-a328-0098ae648f22.png)
> 
>     * task manager 能看到任务进程 → 杀死 → 重开 → 截图如上

生成词库的 bug 也修复了，是重构的时候引入的。可以重新试一下那个漫画，应该不会有问题了。

**Comment by libregd** [comment]
wow, 好快速，感谢你，我再测测有什么意见和bug再提出哈！
