### ISSUE TITLE
桌面版icon

### ISSUE THREAD

**Issue by libregd** [tangshimin/qwerty-learner-desktop#8]
win的taskbar 确实比较小，也和显示屏档次有关系。 看得清，不锯齿还是比较重要。
![sample](https://user-images.githubusercontent.com/59383867/167778093-054f1067-c817-4463-9e04-0c515e608261.png)

做了一些，尺寸是500px 的png，[png以及svg源文件](https://github.com/libregd/warehouse/tree/main/images/qwerty-desktop)

有修改意见欢迎提出。

**Comment by tangshimin** [comment]
没有以前的那种立体效果了，可以把以前的那个图标调整成这种效果吗？ 
图片地址：https://365psd.com/psd/keyboard-button-psd-template-53178
![keyboard-button-psd-template-53178](https://user-images.githubusercontent.com/16540656/167789428-80fc2697-59ef-4e7f-9d2e-a244945946eb.jpg)

**Comment by libregd** [comment]
以前那个不能调，使用的技法不一样，做了一个类似风格的，可以换上看看。
![04](https://github.com/libregd/warehouse/blob/main/images/qwerty-desktop/04.png?raw=true)

**Comment by libregd** [comment]
看了一下上面那个是免费的psd：
![05](https://github.com/libregd/warehouse/blob/main/images/qwerty-desktop/05.png?raw=true)
略作修改有一个：
![06](https://github.com/libregd/warehouse/blob/main/images/qwerty-desktop/06.png?raw=true)

**Comment by tangshimin** [comment]
不要立体感了，windows 的标题栏太小了，立体效果显示不出来，只能简化。
![Snipaste4](https://user-images.githubusercontent.com/16540656/167855002-bec5b99f-a04b-487f-abe4-dc313f61cd53.png)

**Comment by libregd** [comment]
本次交流可以载入设计师沟通案例系列之《用回第一稿》
![07](https://github.com/libregd/warehouse/blob/main/images/qwerty-desktop/07.png?raw=true)

**Comment by tangshimin** [comment]
😊   和第一稿还是不一样的，就用这一张了。

**Comment by tangshimin** [comment]
可以提供最后这个图片的 svg 文件吗？

**Comment by libregd** [comment]
不好意思忘了更新了...
[ver-1-svg](https://github.com/libregd/warehouse/blob/main/images/qwerty-desktop/qwerty-desktop-ver-1.svg)

**Comment by tangshimin** [comment]
这个尺寸太小了，有没有 200 x 200 的？

**Comment by tangshimin** [comment]
这个尺寸做 logo 不合适，特别是 macOS 系统

**Comment by libregd** [comment]
you could export different size and format from [figma](https://www.figma.com/file/4W5IZCBY2jWf6tQ0Mam02I/qwerty-desk?node-id=7%3A2)
